version: '3.1'

volumes:
  data:

services:

  db:
    image: mariadb
    restart: always
    container_name: CMS-Auth-DB
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MYSQL_DATABASE: auth
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3001:3306"
